### ISSUE TITLE
Performance/EndWith not autocorrecting

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop-performance#122]
I was surprised that the following code did not get autocorrected...

```ruby
filename += '.rb' unless filename =~ /\.rb$/
```

**Comment by fatkodima** [comment]
https://github.com/rubocop-hq/rubocop-performance/blob/fd9e06006d415fe155143b6c5367dad4b41628b7/config/default.yml#L128-L139

`.rubocop.yml` should be updated to `AutoCorrect: true` and `SafeMultiline: false` for this to work.

**Comment by koic** [comment]
`Performance/EndWith`'s auto-correct has been enabled by default. https://github.com/rubocop/rubocop-performance/pull/212
OTOH, `SafeMultiline: true` keeps the default for safe detection.
