### ISSUE TITLE
Performance/StringInclude is recommending I replace `match?` with `include?` on a symbol.

### ISSUE THREAD

**Issue by snood1205** [rubocop/rubocop-performance#161]
I generally understand the purpose of replace `#match?` with `#include?` for a literal only regex, but on symbols, only the method `#match?` is defined and not `#include?`

--------

## Expected behavior

```ruby
def clean_up_symbol(symbol)
  symbol.slice(0, 10) if symbol.match?(/foo_bar/)
end
```

## Actual behavior

```ruby
def clean_up_symbol(symbol)
  symbol.slice(0, 10) if symbol.match?(/foo_bar/)
end
```

```
example.rb:2:26: C: Performance/StringInclude: Use String#include? instead of a regex match with literal-only pattern.
  symbol.slice(0, 10) if symbol.match?(/foo_bar/)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

This can be reproduced as above? I'm not entirely sure how to be describe reproduction. 
## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ bundle exec rubocop -V
0.89.1 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-darwin19)
```
From `Gemfile.lock`
```rubocop-performance (1.7.1)```

**Comment by Drenmi** [comment]
RuboCop can only do static analysis. It can not know what type of object `symbol` is during runtime. (Despite the variable being named `symbol`. 🙂 This is a general limitation of what can be done statically, and applies to any object that implements a `#match?` but not an `#include?` method.

**Comment by bquorning** [comment]
I would go with
```rb
symbol.slice(0, 10) if symbol.to_s.include?('foo_bar')
```
`Symbol#match?` converts its argument to a string anyway, so there should be no overhead by calling `to_s` explicitly.

**Comment by koic** [comment]
This cop has been marked `SafeAutoCorrect: false`. I will close this issue. Thank you.
