### ISSUE TITLE
Feature request: encourage `Enumerable#filter_map`

### ISSUE THREAD

**Issue by ghiculescu** [rubocop/rubocop-performance#178]
https://blog.saeloun.com/2019/05/25/ruby-2-7-enumerable-filter-map.html 

This was introduced in ruby 2.7. It adds a modest speedup over `.map {}.compact` or `.select {}.map {}`.

**Comment by koic** [comment]
This is a note about an incompatibility between `filter_map` and `compact`. `filter_map` excludes `false` unlike `compact`.

```ruby
[true, false, nil].compact              #=> [true, false]
[true, false, nil].filter_map(&:itself) #=> [true]
```
