### ISSUE TITLE
Preformance/RedundantEqualityComparisonBlock is incorrect

### ISSUE THREAD

**Issue by twalpole** [rubocop/rubocop-performance#225]
For code like

    items.any? { |item| item === pattern }

the cop is reporting/autofixing with

    items.any?(pattern)

This is incorrect since `any?` with a pattern is equivalent to

    items.any? { |item| pattern === item }

https://ruby-doc.org/core-2.5.1/Enumerable.html#method-i-any-3F

**Comment by marcandre** [comment]
Indeed, we should assume that the order with `===` is very important, contrary to `==`
