### ISSUE TITLE
RedundantEquality check auto-correct false positive

### ISSUE THREAD

**Issue by michaelglass** [rubocop/rubocop-performance#231]
Original code

```ruby
segments.all? { |segment| segment.uniq == segment }
```

## Expected behavior
Do nothing

## Actual behavior
autocorrected to
```ruby
segments.all?(segment.uniq)
```

## Steps to reproduce the problem
```sh
$ echo "segments.all? { |segment| segment.uniq == segment }" > foo.rb
$ rubocop -A foo.rb
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.12.0 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 2.6.6 x86_64-darwin17)
  - rubocop-performance 1.10.2
  - rubocop-rails 2.9.1
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.2.0
  - rubocop-sorbet 0.6.1
```

(rubocop-performance is wonderful, thank you for it!)

**Comment by koic** [comment]
`segments.all? { |segment| segment.uniq == segment }` makes comparison by `==`, however `segments.all?(segment.uniq)` makes comparison by `===`. Therefore as documented, this cop has been already marked as unsafe.

- https://docs.rubocop.org/rubocop-performance/1.10/cops_performance.html#performanceredundantequalitycomparisonblock
- https://github.com/rubocop/rubocop-performance/blob/v1.10.2/config/default.yml#L209

> $ rubocop -A foo.rb

And `rubocop -A` option is for unsafe auto-correction (`rubocop -a` option is for safe auto-correction).
https://docs.rubocop.org/rubocop/1.3/usage/auto_correct.html

Thank you.
