### ISSUE TITLE
Performance/RedundantEqualityComparisonBlock incorrect detecting with parallel assignment

### ISSUE THREAD

**Issue by AndreiEres** [rubocop/rubocop-performance#234]
I found incorrect detecting. That sample
```ruby
detections.all? { |detected_style,| detected_style == :unannotated }
```

has correctable offence `Performance/RedundantEqualityComparisonBlock: Use all?(:unannotated) instead of block.`.

It's wrong because here we use parallel assignment. I assume that detections consists of arrays and `all?(:unannotated)` will ever return only false.

--------

## Expected behavior

I expect no offences in that case.

## Actual behavior

Incorect correction.

## Steps to reproduce the problem

Check this sample 
```ruby
detections.all? { |detected_style,| detected_style == :unannotated }
```

## RuboCop version
```
$ [bundle exec] rubocop -V
bundle exec rubocop -V
1.12.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin20)
  - rubocop-performance 1.10.1
  - rubocop-rspec 2.2.0
```

**Comment by koic** [comment]
This issue has been resolved by https://github.com/rubocop/rubocop-performance/pull/224 and released. Can you update RuboCop Performance to 1.10.2? Thank you.
