### ISSUE TITLE
RedundantStringChars auto-correct

### ISSUE THREAD

**Issue by jaycetde** [rubocop/rubocop-performance#249]
```ruby
str = ''

# Existing code:
str.chars.last(2)
  # => []

# Rubocop suggested and auto-corrected to:
str[-2..-1].chars
  # => NoMethodError (undefined method `chars' for nil:NilClass)
# Not equivalent to `str.chars.last(2)` because below returns `nil`
str[-2..-1]
  # => nil
```

--------

## Expected behavior

Do not set this cop as auto-correctable as it can cause breakage

## Actual behavior

Auto-correct transforms into potentially broken code

## Steps to reproduce the problem

NA

## RuboCop version

```
$ [bundle exec] rubocop -V
1.14.0 (using Parser 3.0.1.1, rubocop-ast 1.5.0, running on ruby 2.5.7 x86_64-linux)
  - rubocop-performance 1.6.1
  - rubocop-rails 2.5.2
```

**Comment by jjb** [comment]
I experienced `string.chars[0]` → `string[0].chars`

rubocop-performance 1.11.5 (held back by standardrb)

**Comment by koic** [comment]
@jjb Thank you for the feedback. I've opened #273.
