### ISSUE TITLE
UnfreezeString autocorrect incorrectly handles .force_encoding

### ISSUE THREAD

**Issue by johnnyshields** [rubocop/rubocop-performance#252]
The autocorrect for:

```
String.new.force_encoding('Ascii')
```

gave me:

```
# BAD - raises FrozenError (can't modify frozen String)
+''.force_encoding('Ascii')
```

Instead it should add parenthesis

```
# GOOD
(+'').force_encoding('Ascii')
```

Please check if there are other affected methods... I haven't tested but imagine you are already handling bang (!) methods properly.

**Comment by koic** [comment]
`+'str'.do_something` is equivalent to `+('str'.do_something)`, not `(+'str').do_something`. So, other than `force_encoding` method may be unintended. I opened #253 that consistent adding parentheses if a method call after an offense code.

**Comment by johnnyshields** [comment]
Wonderful, thanks for the prompt response!
