### ISSUE TITLE
MapCompact cop is not correct because it does not give equivalent results

### ISSUE THREAD

**Issue by Viktor-Ivliev** [rubocop/rubocop-performance#280]
There are a lot of cases when we need to filter out only nil values, compact is used for this. This cop suggests replacing it with filter map, but then the application logic becomes incorrect, since filter_map also filters out the fasle values.

Cop should offer such constructions after the application of which, the logic of the application does not change.

--------

## Expected behavior

    # [true, false, nil] send construction of the map+compact equivalent          #=> [true, false]

## Actual behavior

https://github.com/koic/rubocop-performance/blob/f45a3238ac353b73380d971cda918dcd15f164ab/lib/rubocop/cop/performance/map_compact.rb#L17

      # [true, false, nil].compact              #=> [true, false]
      # [true, false, nil].filter_map(&:itself) #=> [true]

**Comment by koic** [comment]
The cop has been marked as unsafe auto-correction.
https://github.com/rubocop/rubocop-performance/blob/v1.13.1/config/default.yml#L189

That is, it will not auto-corrected with `-a` safe option, it will auto-corrected with `-A` unsafe option.
https://docs.rubocop.org/rubocop/1.24/usage/auto_correct.html
