### ISSUE TITLE
Performance/MapCompact autocorrect breaks code logic

### ISSUE THREAD

**Issue by MrEmelianenko** [rubocop/rubocop-performance#306]
**Problem:**
I use `map(...).compact` in my code. Rubocop offers to replace it with `filter_map(...)`, but it breaks the logic.

**Reason:**
`filter_map` filters `false` and `nil` values.
`compact` filters only `nil` values.

--------

## Expected behavior

I expect Rubocop autocorrect not to break code logic :)

## Actual behavior

Autocorrect changes the behaviour of the code.

## Steps to reproduce the problem

Here is the code example:

```ruby
# frozen_string_literal: true

require "ostruct"

response1 = OpenStruct.new(marks_visible: true)
response2 = OpenStruct.new(marks_visible: false)
response3 = OpenStruct.new(marks_visible: nil)

puts "Result 1:"
pp [response1, response2, response3]
  .map(&:marks_visible)
  .compact

puts "Result 2:"
pp [response1, response2, response3]
  .filter_map(&:marks_visible)
```

Here is the output of this code:
```
Result 1: [true, false]
Result 2: [true]
```

## RuboCop version

```
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2) [arm64-darwin21]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.15.2
  - rubocop-rspec 2.12.1
```

**Comment by koic** [comment]
Yeah, `Performance/MapCompact` cop is already marked unsafe because the incompatibility. See the documentation for details. Thank you.
https://docs.rubocop.org/rubocop-performance/1.15/cops_performance.html#performancemapcompact
