### ISSUE TITLE
match? is suggested when TargetRubyVersion: 2.3

### ISSUE THREAD

**Issue by pboling** [rubocop/rubocop-performance#322]
`Regexp.match` method is in [Ruby 2.3+](https://docs.ruby-lang.org/en/2.3.0/Regexp.html#method-i-match)
`Regexp.match?` method is in [Ruby 2.4+](https://docs.ruby-lang.org/en/2.4.0/Regexp.html#method-i-match-3F)

--------

## Expected behavior

I have TargetRubyVersion set to `2.3`, so it should not be auto-correcting a change to `match?`, which causes a `NoMethodError` on Ruby 2.3.

## Actual behavior

It auto-corrects to `match?`:
```
$ bundle exec rubocop -a
Inspecting 131 files
...C....................................................C....................................................................C.....

Offenses:

README.md:1255:10: C: [Corrected] Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
      if table =~ /^#{Dynamoid::Config.namespace}/
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/dynamoid/finders.rb:297:12: C: [Corrected] Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
        if method =~ /find/
           ^^^^^^^^^^^^^^^^
lib/dynamoid/finders.rb:306:14: C: [Corrected] Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
          if finder =~ /all/
             ^^^^^^^^^^^^^^^
spec/support/delete_all_tables_in_namespace.rb:7:49: C: [Corrected] Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
        Dynamoid.adapter.delete_table(table) if table =~ /^#{Dynamoid::Config.namespace}/
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

Failed build example on Ruby 2.3:
https://github.com/Dynamoid/dynamoid/actions/runs/3717851355/jobs/6305609648#logs

Note that builds with later versions of Rails (5.1+) pass because Rails has backfilled `match?`.

## RuboCop version

```
$ bundle exec rubocop -V
0.81.0 (using Parser 3.1.3.0, running on ruby 2.4.10 x86_64-darwin19)
```

The old version of RuboCop, is not relevant to the problem, as it does support TargetRubyVersion.

**Comment by koic** [comment]
The issue does not reproduce with the latest RuboCop. Can you upgrade RuboCop and RuboCop Perfomance to the latest version?

```console
% bundle exec rubocop -V
1.40.0 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.1.1) [x86_64-darwin19]
  - rubocop-minitest 0.25.0
  - rubocop-performance 1.15.1
  - rubocop-rails 2.17.3

% cat .rubocop.yml
AllCops:
  TargetRubyVersion: 2.3

% cat example.rb
if finder =~ /all/
  foo
end

% bundle exec rubocop
(snip)

Inspecting 1 file
C

Offenses:

example.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
if finder =~ /all/
^
example.rb:1:1: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if finder =~ /all/
^^

1 file inspected, 2 offenses detected, 2 offenses autocorrectable
```

Thank you.

**Comment by pboling** [comment]
I've been avoiding the RuboCop upgrade, but as this is something solved by improvements to the AST, or RuboCop proper, I'll have to rethink my approach to locking rubocop to very old versions when I'm supporting very old Ruby.

Thanks!  I had not, until this moment, had a solid reason for upgrading.

**Comment by koic** [comment]
Yeah, the latest RuboCop 1.40 requires Ruby 2.6+ at runtime, but supports analysis `TargetRubyVersion` from 2.0 to 3.1!
https://docs.rubocop.org/rubocop/1.40/compatibility.html
