### ISSUE TITLE
`alias` vs method call

### ISSUE THREAD

**Issue by fatkodima** [rubocop/rubocop-performance#324]
Calling a method defined via `alias` is 30% faster than via an inner method call.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "benchmark-ips"
end

class Foo
  def foo
    2
  end

  def bar
    foo
  end

  alias baz foo
end

f = Foo.new

Benchmark.ips do |x|
  x.report("calling") do
    f.bar
  end

  x.report("alias") do
    f.baz
  end

  x.compare!
end
```

```
Warming up --------------------------------------
             calling   957.809k i/100ms
               alias     1.203M i/100ms
Calculating -------------------------------------
             calling      9.218M (± 0.8%) i/s -     46.933M in   5.091768s
               alias     12.059M (± 0.3%) i/s -     61.345M in   5.087147s

Comparison:
               alias: 12058838.1 i/s
             calling:  9217894.7 i/s - 1.31x  (± 0.00) slower
```

I recently applied such optimization in the hot codepath in `rubocop-ast` (https://github.com/rubocop/rubocop-ast/pull/249/files#diff-22465a88b22d087c315ea77d380acb9564656d0a083bac453f4c5e432c5b1897R218).

**Comment by fatkodima** [comment]
Gave this idea another thought. While it is definitely faster, semantically `alias` is not the same as one method calling another. `alias` is like a second/another name (like `append` and `push`; `allow_something` and `allow_something?`) of the same thing/action. But one method calling another - is an implementation detail of the caller. 

It will produce a lot of cases where it is better as it was. For example, https://github.com/rubocop/rubocop/blob/3a542a96fb59c254d68348c54e04af8fdcab7b4e/lib/rubocop/cli/command/show_cops.rb#L19-L21 or https://github.com/rubocop/rubocop/blob/3a542a96fb59c254d68348c54e04af8fdcab7b4e/lib/rubocop/cop/layout/multiline_array_brace_layout.rb#L109-L111. 

I kinda started to implement this cop, but running it on a few projects revealed like 95% of false positives. So I am voting to close this issue.

**Comment by koic** [comment]
I agree to close this proposal. Thank you for investigating!
