### ISSUE TITLE
Misleading suggestion from `Performance/DeletePrefix` cop

### ISSUE THREAD

**Issue by ashmaroli** [rubocop/rubocop-performance#335]
## Expected behavior

Expected RuboCop Performance to not flag reported method as an offense.

## Actual behavior

RuboCop Performance flagged the reported method as an offense and recommended replacing the `gsub` call with `delete_prefix` call.

```
C: [Correctable] Performance/DeletePrefix: Use delete_prefix instead of gsub.
```
*The suggestion is misleading because `delete_prefix` works akin to `sub` in that only the first encountered match is deleted in contrast to `gsub` which continues deleting matches beyond the first match.*

## Steps to reproduce the problem

```ruby
# Utility method to ensure that given +input+ string starts
# with a single forward-slash.
# If given input starts with multiple slashes, a copy of the
# input is returned after stripping extra slashes.
def Foo.ensure_single_leading_slash(input)
  result = input.to_s.gsub(/\A\//, '')
  "/#{result}"
end
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:
You can see extension cop versions (e.g. rubocop-performance, rubocop-rails, and others) output by `rubocop -V`,
include them as well. Here's an example:

```
1.38.0 (...)
  - rubocop-performance 1.15.0
```

**Comment by fatkodima** [comment]
`/\Asomething/` regexp will match maximum 1 substring of the string (at the beginning of the string), so `gsub` will only delete the first occurrence (if any) at the beginning of the string, so acts like `sub`.

**Comment by ashmaroli** [comment]
Apparently, you're right, @fatkodima. My tests were wrong.
Sorry for the noise.
