### ISSUE TITLE
Performance/Detect suggests reverse.find should be used on hash but reverse doesn't exist

### ISSUE THREAD

**Issue by ekohl** [rubocop/rubocop-performance#336]
`Hash` does not inherit Enumerable so `reverse` does not exist on it, but it does implement some methods with the same interface, such as `select` and `find_all`.

This came from a regression introduced in https://github.com/puppetlabs/puppetlabs_spec_helper/commit/24d92da1ce27de1fcd532dfaac440233429b7a0f#diff-77f5c8eb6c2374258943fce12a490c421cf882db8f8fdec3bd02e74bc76fac85L319

## Steps to reproduce the problem

A simplified version of the above code is:

```ruby
x = {}
x.select { |_k, v| v.key?('thread') }.last
```

## Expected behavior

Ideally Rubocop would be able to figure out that the variable `x` is a hash and accept it as valid code.

## Actual behavior

It finds an offense and makes an invalid suggestion.
```
test.rb:2:3: C: [Correctable] Performance/Detect: Use reverse.find instead of select.last.
x.select { |_k, v| v.key?('thread') }.last
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## RuboCop version

```console
$ bundle exec rubocop -V
1.6.1 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.1.3 x86_64-linux)
  - rubocop-performance 1.9.2
  - rubocop-rspec 2.0.1
```

**Comment by fatkodima** [comment]
This cop is already marked as not safe - https://github.com/rubocop/rubocop-performance/blob/a28bd39216d265e8b1079c5f34b5b97c9f9c9766/lib/rubocop/cop/performance/detect.rb#L10-L13 so this is expected.

> Ideally Rubocop would be able to figure out that the variable x is a hash and accept it as valid code.

Rubocop does static analysis of the code, so it is unable to know which type `x` will have at runtime.

**Comment by ekohl** [comment]
I agree, hence the word "ideally".

Perhaps the description could be enhanced to also mention it's not just external libraries/frameworks but also built in classes.

**Comment by fatkodima** [comment]
> Perhaps the description could be enhanced to also mention it's not just external libraries/frameworks but also built in classes.

Would you like to open a PR?
