### ISSUE TITLE
Problem with BigDecimalWithNumericArgument cop

### ISSUE THREAD

**Issue by tycooon** [rubocop/rubocop-performance#468]
I have the following code in my app: 

```
BigDecimal("1.0")
```

Latest rubocop autocorrects it to the following:

```
BigDecimal(1.0)
```

The problem is it does not work and I get error:

```
     ArgumentError:
       can't omit precision for a Float.
```

```
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.5) [arm64-darwin23]
  - rubocop-factory_bot 2.26.1
  - rubocop-performance 1.22.0
  - rubocop-rails 2.26.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 3.0.5
```

**Comment by koic** [comment]
This issue has been fixed in RuboCop Performance 1.22.1. Thank you for the feedback!
https://github.com/rubocop/rubocop-performance/releases/tag/v1.22.1
