### ISSUE TITLE
Cop idea: prefer `String#bytesize` over `String#bytes#size`

### ISSUE THREAD

**Issue by viralpraxis** [rubocop/rubocop-performance#475]
I've seen some developers using `some_string.bytes.size` (or `count`/`length`) instead of the constant-time `String#bytesize` method.

In MRI there is no copy-on-write optimization for string/array conversion, so for large strings, the unnecessary array allocation could result in performance issues
```
require "objspace"

s = "a" * 1_000_000
initial = ObjectSpace.count_objects_size[:T_ARRAY]
b = s.bytes.count
p (ObjectSpace.count_objects_size[:T_ARRAY] - initial) / (1 << 10)

> 7812
```

I've opened https://github.com/rubocop/rubocop-performance/pull/474 which will be finished if the idea accepted

**Comment by dvandersluis** [comment]
This makes sense as a cop to me. The link you included in the PR (https://github.com/fastruby/fast-ruby#remove-extra-spaces-or-other-contiguous-characters-code) doesn't mention bytesize though, is there another source?

**Comment by viralpraxis** [comment]
I copy-pasted it from another config entry, that `Reference` key is obsolete in this case

**Comment by viralpraxis** [comment]
The PR is ready for review
