### ISSUE TITLE
EndWith/StartWith autocorrects are not nil-safe

### ISSUE THREAD

**Issue by dduugg** [rubocop/rubocop-performance#50]
The `EndWith`/`StartWith` autocorrects do not contemplate `nil`. I propose modifying them to behave like `RegexpMatch` (which corrects `do_something if pattern =~ param` into `do_something if pattern&.match?(path)`

## Expected behavior

`do_something if var =~ /\A#/` should autocorrect to `do_something if var&.start_with?('#')`

Since it appears rubocop will soon [end support](https://github.com/rubocop-hq/rubocop/issues/6945) for pre-2.3 ruby, I propose only fixing this for ruby 2.3 and above (where safe navigation is available).

## Actual behavior

`do_something if var =~ /\A#/` autocorrects to `do_something if var.start_with?('#')`. The correction will now raise a `NoMethodError` when `var` is `nil`, where previously the condition would simply evaluate to `nil`.

## Steps to reproduce the problem

Invoke `rubocop -a --only Performance/StartWith` on a file containing `do_something if var =~ /\A#/`, with a `.rubocop.yml` file containing:
```
require:
  - rubocop-performance
Performance/StartWith:
  AutoCorrect: true
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ bundle exec rubocop -V
0.68.0 (using Parser 2.6.0.0, running on ruby 2.4.5 x86_64-darwin17)
```

**Comment by koic** [comment]
This cop is marked `SafeAutoCorrect: false` and unmarked `AutoCorrect: false`. So I will close this issue. Thank you.
