### ISSUE TITLE
[Propose] Use different default config name as rubocop's "default.yml" 

### ISSUE THREAD

**Issue by zw963** [rubocop/rubocop-performance#59]
I thought there maybe some users use rubocop like me, As a standalone syntax checker, for all our project,  please see [this](https://github.com/zw963/ruby_tools/tree/master/app/config).

So, when no ruby gems managered, (e.g. only use $LOAD_PATH), i have to change `rubocop-performance` config file to a different name, and [hack](https://github.com/zw963/ruby_tools/blob/master/app/lib/rubocop/performance.rb#L7) code to make it work, that not good.

so, i propose to use a seperate name, Thanks!

**Comment by koic** [comment]
AFAIK, I haven't heard of the issue from other use cases. And I haven't started this for now due to this change may be breaking change, so I'll close this one. Thank you. (It's possible that my understanding isn't enough because the links are 404 not found.)

**Comment by zw963** [comment]
It's okay for me now, because i am separate different config into individual folder, as normal gem does. thank you.
